#!/bin/sh -e
# Accepted values: postgres, kafka, redis, google-cloud-pubsub
# If no variable provided all services will start
if [ -n "$1" ]; then
    if [ "$1" != "kafka" ] && [ "$1" != "redis" ] && [ "$1" != "postgres" ] && [ "$1" != "google-cloud-pubsub" ]; then
        echo  "Not a valid value. Choose one or none:
    kafka
    redis
    postgres
    google-cloud-pubsub ";
        exit 1;
    fi
fi

docker-compose up $1
